stdfunc - add find python interpreter path.

diff --git a/bashrc/stdfunc b/bashrc/stdfunc
--- a/bashrc/stdfunc
+++ b/bashrc/stdfunc
@@ -316,6 +316,14 @@ assert_interactive() {
   fi
 }
 
+which_python() {
+    for python in /usr/bin/python2.6 /usr/bin/python2.7 /usr/bin/python; do
+        test -x "$python" && echo "$python" && return
+    done
+    echo >&2 'Could not find a Python interpreter.'
+    exit 1
+}
+
 assert_not_root_user
 assert_root_user
 error "Bad news"
